version: 2

project_name: diffly

builds:
  - id: diffly
    builder: rust
    tool: cross
    command: build
    binary: diffly
    flags:
      - --release
      - --locked
      - --features=cli
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-msvc
      - x86_64-unknown-freebsd
      - x86_64-unknown-netbsd

archives:
  - id: default
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: "diffly_{{ .Version }}_{{ .Target }}"
    files:
      - README.md
      - LICENSE-MIT
      - LICENSE-APACHE

checksum:
  name_template: "diffly_{{ .Version }}_checksums.txt"

release:
  github:
    owner: kodaskills
    name: diffly
  draft: false
  prerelease: auto

changelog:
  disable: true
